### ISSUE TITLE
Posssibility to ignore .gitignore for PRs

### ISSUE THREAD

**Issue by sogehige** [crowdin/github-action#116]
Currently I've got all locales except english in .gitignore to not commit those files manually. This is causing to pull request don't add downloaded translation files. Is it possible to make pull request with ignored files/

**Comment by DimaYashchyshyn** [comment]
hi @sogehige 
I guess no, you have all files in ignorance pattern for now 

Please share your configuration (without any credentials). I'd like like to investigate it and propose something to help on the matter

**Comment by sogehige** [comment]
I simply just removed .gitignore entries affecting locales. 

my .gitignore change: https://github.com/sogebot/sogeBot/commit/56ae28facf29cf64105f56d769753635c6ebe9cf

https://github.com/sogebot/sogeBot/blob/master/.github/workflows/crowdin.yml
https://github.com/sogebot/sogeBot/blob/master/crowdin.yml

**Comment by Natalia936** [comment]
Hi @sogehige , we'll check it and get back to you

**Comment by andrii-bodnar** [comment]
Hi @sogehige,

Currently, the Action doesn't support adding ignored files since it's based on `git add` and it could be dangerous to force `add` files along with ignored files

There is no need to gitignore localization files. Since the translations management will be in Crowdin, the translation files shouldn't be edited locally.
