### ISSUE TITLE
Warn that this is a paid only integration for Crowdin

### ISSUE THREAD

**Issue by lil5** [crowdin/github-action#131]
No where on the [readme](https://github.com/crowdin/github-action#readme), [Pricing page](https://crowdin.com/pricing), [Marketplace](https://crowdin.com/resources/marketplace/github-action) is it stated that this is for _paying customers_

![Screenshot_2022-06-16_13-04-45](https://user-images.githubusercontent.com/17646836/174056996-443a5c9e-18f0-4251-8152-a334390bef61.png)

---

**UploadTranslations**

**Url:** https://api.crowdin.com/api/v2/projects/12345/translations/nl
**Method:** POST
**Status:** Error
**Message:** Payment Required
**Authorization Type:** Personal Access Token

```json
{
    "error": {
        "message": "Organization is currently suspended",
        "code": 402
    }
}
```

**Comment by Andrulko** [comment]
It shouldn't be paid, all paid apps have corresponding labels (there are just a few):
https://crowdin.com/resources/marketplace/marketo-app
https://crowdin.com/resources/marketplace/salesforce-experience-builder
https://crowdin.com/resources/marketplace/salesforce-knowledge

Any chance that you've reached your organization's limits in GitHub? GitHub Action itself is a paid feature:
https://github.com/pricing

A free version allows 2000 minutes/month. Anyway, it seems to be a message from Crowdin, so we're checking it furthermore. Thanks for the report!

**Comment by lil5** [comment]
> Apologies for the confusion!

To remove confusion please remove the `free` badge on the marketplace

**Comment by Andrulko** [comment]
My apologies for not being clear in my previous reply, it really depends on the plan status as @andrii-bodnar has mentioned. GitHub Action is available for any plan (including the Free plan) but not for an expired free trial.

When your free trial expires (it's not the same as the Free plan), API is not available therefore you cannot submit API requests via CLI/API/GHA.

**Comment by lil5** [comment]
That sounds pretty convenient to call something free which is actually (only during trail)

A consistent method for trail naming is that the trail is a way to explore paid exclusives for a limited time for free. Not that free stuff is actually not free.

**Comment by Andrulko** [comment]
The "_Free_" label means that the connector/tool is not paid extra. Crowdin has a Free plan, it has some limitations described here (like 1 private project / unlimited translators in the public projects only):
https://crowdin.com/pricing

A free 15 days trial allows you to evaluate all features that are available, then you can decide what plan works the best for you and use additional extensions (like GitHub Action) without extra fees.

When the free trial expires, we add limitations (e.g. it's not possible to push new content). It is fair, since it won't be possible to view the uploaded content in the translations editor due to it's not available when the trial is over. Mainly all connectors synchronize the content via API, this is why they become unavailable when the subscription is not active / free plan is not activated.

In any case, we have 24/7 support, your account can be re-activated per request if you need more time to evaluate the platform

Hope it makes some sense 🤲
